#!/usr/bin/env python3
"""Post an adjudicated review.json to a GitHub PR as one review with inline
comments.

Deterministic delivery: the model decides nothing here. The script parses the
final ``ReviewReport`` through ``schema.py`` (so only contract-valid findings
can ever reach a PR), builds a single ``POST /pulls/{n}/reviews`` payload with
one inline comment per finding plus a verdict summary body, and submits it
via the ``gh`` CLI. The review event is always ``COMMENT`` -- a bot that
blocks merges by default is hostile; the verdict is stated in the body and
the humans decide.

If GitHub rejects the inline batch (typically 422: a cited line is not part
of the PR diff), the script falls back to a single ``gh pr comment`` whose
body embeds every finding, so nothing is silently lost.

Usage:
    python3 post_pr_comments.py <review.json> --pr <number> [--repo o/r]
                                [--dry-run]

Exit codes: 0 posted (or dry-run), 1 invalid report, 2 usage/gh failure.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from types import ModuleType
from typing import Final, Protocol

_SCHEMA_PATH: Final = Path(__file__).resolve().parent.parent / "skills" / "review-contract" / "schema.py"


# schema.py is loaded dynamically (its directory name is not importable), so
# static checkers cannot see its types. These Protocols pin the exact surface
# this script consumes; schema.py's frozen dataclasses satisfy them.


class _EnumLike(Protocol):
    @property
    def value(self) -> str: ...


class FindingLike(Protocol):
    @property
    def severity(self) -> _EnumLike: ...
    @property
    def dimensions(self) -> Sequence[_EnumLike]: ...
    @property
    def file(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def end_line(self) -> int | None: ...
    @property
    def summary(self) -> str: ...
    @property
    def why(self) -> str: ...
    @property
    def fix(self) -> str: ...
    @property
    def confidence(self) -> int: ...
    @property
    def location(self) -> str: ...


class ReportLike(Protocol):
    @property
    def verdict(self) -> _EnumLike: ...
    @property
    def summary(self) -> str: ...
    @property
    def actions(self) -> Sequence[str]: ...
    @property
    def findings(self) -> Sequence[FindingLike]: ...


def _load_schema() -> ModuleType:
    spec = importlib.util.spec_from_file_location("review_schema", _SCHEMA_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load schema module at {_SCHEMA_PATH}")
    module = importlib.util.module_from_spec(spec)
    # dataclass(slots=True) resolves cls.__module__ via sys.modules during
    # class creation, so the module must be registered before execution.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _gh(args: list[str], *, stdin: str | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["gh", *args],
        input=stdin,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )


def _repo_slug(explicit: str | None) -> str:
    if explicit:
        return explicit
    proc = _gh(["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"])
    if proc.returncode != 0:
        raise RuntimeError(f"gh repo view failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def _head_sha(pr: int, repo: str) -> str:
    proc = _gh(["pr", "view", str(pr), "--repo", repo, "--json", "headRefOid", "-q", ".headRefOid"])
    if proc.returncode != 0:
        raise RuntimeError(f"gh pr view failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def _comment_body(finding: FindingLike) -> str:
    dims = ", ".join(d.value for d in finding.dimensions)
    return (
        f"**{finding.severity.value}** ({dims}, confidence "
        f"{finding.confidence}) — {finding.summary}\n\n"
        f"**Why:** {finding.why}\n\n"
        f"**Suggested fix:** {finding.fix}"
    )


def _review_body(report: ReportLike) -> str:
    lines = [
        f"## Code Review — verdict: **{report.verdict.value}**",
        "",
        report.summary,
    ]
    if report.actions:
        lines += ["", "**Top actions:**"]
        lines += [f"{i}. {a}" for i, a in enumerate(report.actions, start=1)]
    lines += ["", "_Generated by omniagents-reviewer (adjudicated)._"]
    return "\n".join(lines)


def _fallback_body(report: ReportLike) -> str:
    lines = [_review_body(report), "", "### Findings", ""]
    for f in report.findings:
        lines.append(f"- `{f.location}` — {_comment_body(f)}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = argv[1:]
    if not args or "--pr" not in args:
        print(__doc__, file=sys.stderr)
        return 2
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    def _flag_value(flag: str) -> str | None:
        if flag in args:
            at = args.index(flag)
            if at + 1 >= len(args):
                print(f"{flag} requires a value", file=sys.stderr)
                raise SystemExit(2)
            value = args[at + 1]
            del args[at : at + 2]
            return value
        return None

    pr_raw = _flag_value("--pr")
    repo_flag = _flag_value("--repo")
    if pr_raw is None or not pr_raw.isdigit() or not args:
        print(__doc__, file=sys.stderr)
        return 2
    pr = int(pr_raw)
    review_path = Path(args[0])

    schema = _load_schema()
    try:
        raw: object = json.loads(review_path.read_text(encoding="utf-8"))
        report: ReportLike = schema.ReviewReport.from_json(raw)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        # ContractError subclasses ValueError; the class object lives in the
        # dynamically loaded module, so catch the stable stdlib base.
        print(json.dumps({"error": f"invalid review.json: {exc}"}), file=sys.stderr)
        return 1

    # Same confidence floors the renderer applies to review.md -- a finding
    # too weak for the local report must never reach a public PR.
    report, floor_warnings = schema.enforce_confidence(report)
    for warning in floor_warnings:
        print(json.dumps({"warning": warning}), file=sys.stderr)

    try:
        repo = _repo_slug(repo_flag)
        head = _head_sha(pr, repo)
    except RuntimeError as exc:
        if not dry_run:
            print(json.dumps({"error": str(exc)}), file=sys.stderr)
            return 2
        # Dry-run must work offline: show the payload with placeholders.
        repo = repo_flag or "<owner>/<repo>"
        head = "<head-sha>"
        print(json.dumps({"warning": f"dry-run placeholders: {exc}"}), file=sys.stderr)

    comments: list[dict[str, object]] = []
    for f in report.findings:
        comment: dict[str, object] = {
            "path": f.file,
            "line": f.end_line if f.end_line is not None else f.line,
            "side": "RIGHT",
            "body": _comment_body(f),
        }
        if f.end_line is not None and f.end_line != f.line:
            comment["start_line"] = f.line
            comment["start_side"] = "RIGHT"
        comments.append(comment)

    payload = {
        "commit_id": head,
        "event": "COMMENT",
        "body": _review_body(report),
        "comments": comments,
    }

    if dry_run:
        print(json.dumps({"repo": repo, "pr": pr, "payload": payload}, indent=2))
        return 0

    proc = _gh(
        ["api", f"repos/{repo}/pulls/{pr}/reviews", "--method", "POST", "--input", "-"],
        stdin=json.dumps(payload),
    )
    if proc.returncode == 0:
        print(json.dumps({"posted": "review", "inline_comments": len(comments)}))
        return 0

    # Typically 422: some finding cites a line outside the PR diff. Degrade
    # to one summary comment carrying every finding so nothing is lost.
    print(
        json.dumps({"warning": f"inline review rejected: {proc.stderr.strip()[:300]}"}),
        file=sys.stderr,
    )
    fallback = _gh(
        ["pr", "comment", str(pr), "--repo", repo, "--body-file", "-"],
        stdin=_fallback_body(report),
    )
    if fallback.returncode != 0:
        print(
            json.dumps({"error": f"fallback comment failed: {fallback.stderr.strip()}"}),
            file=sys.stderr,
        )
        return 2
    print(json.dumps({"posted": "summary-comment", "findings": len(report.findings)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
